kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubesys-rolebinding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: kubesys-sa
  namespace: kube-system
roleRef:
  kind: Role
  name: kubesys-role
  apiGroup: rbac.authorization.k8s.io
