kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubesys-rolebind
  namespace: kube-system
subjects:
- kind: User
  name: kubesys-sa
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: kubesys-role
  apiGroup: rbac.authorization.k8s.io
